name: margarita
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider_plus: ^6.0.0+1
  camera: ^0.11.0+2
  location: ^7.0.1
  permission_handler: ^11.3.1
  path_provider: ^2.0.12
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  image_picker: ^1.1.2
  geolocator: ^9.0.2
  intl: ^0.18.1
  slide_to_act: ^2.0.1
  flutter_rating_bar: ^4.0.1
shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true # Enable Android icon generation
  ios: true # Enable iOS icon generation (optional, set to false if not needed)
  image_path: "assets/images/logo.png" # Path to your logo.png
  adaptive_icon_background: "#FFFFFF" # Optional: Background color for adaptive icons (Android)
  adaptive_icon_foreground: "assets/images/logo.png" # Optional: Foreground image for adaptive icons (Android)
